### ISSUE TITLE
A little bug saving a filtred file

### ISSUE THREAD

**Issue by pgr123** [Axel-Erfurt/m3uEdit#2]
Good morning,
Bravo for m3uEdit, it is great but I have a little bug when I filter a m3u file and then if I sanve the filtered file, the first line is still missing !
How can I repair this little bug ?
Thank you.
Have a good day.
Best regards.

Pascal

**Comment by Axel-Erfurt** [comment]
Thanks, please try again

I've changed line 602 to

```python
for x in range(0, len(mylist)):
```
